Update README.md
franziskakoellschen/kinoticketreservierung_backend pull request #25
Opened 2021-11-30 11:16 UTC by GregorMuenker

## Pull Request:

## Definition of Done

Add DATABASE_URL to Readme

2021-11-30 12:05 UTC, niklasweidenfeller approved these changes

2021-11-30 12:24 UTC, niklasweidenfeller requested changes

2021-11-30 12:24 UTC, niklasweidenfeller commented on README.md
Vielleicht noch das Lombok Plugin für VS Code / IntelliJ erwähnen

2021-12-10 08:26 UTC, maxlautenbach commented on README.md
Done.

2021-12-10 08:29 UTC, niklasweidenfeller approved these changes

2021-12-10 08:30 UTC, merged